Repository ViktoryiaKurs/probable-octo-waddle, pull requests merged in 2025-04, with the labels that each got.

#1 Add homework 1
  src/homework/hw1oop/task3/BankAccount.java
  src/homework/hw1oop/task3/Main.java
Labels: ready for merge

#2 Грокаем алгосы. Бинарный поиск
  binary_search/untitled/.gitignore
  binary_search/untitled/src/BinSort.java
  binary_search/untitled/src/Main.java
Labels: noice

#6 Yan/hw2/generics
  src/homework/hw2generics/box/Box.java
  src/homework/hw2generics/box/Main.java
Labels: ready for review, ready for merge

#4 Добавил рекурсивный подсчет суммы
  sum/.gitignore
  sum/src/Main.java
  sum/src/Operations.java
Labels: ready for review
